version: '3.8'

services:
  mongodb:
    image: mongo:8.0.4
    container_name: discord-trade-exec-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: devpassword
      MONGO_INITDB_DATABASE: discord_trade_exec
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./scripts/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - trade-exec-network

  redis:
    image: redis:7.0-alpine
    container_name: discord-trade-exec-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass devpassword
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - trade-exec-network

  # Optional: Redis Commander for Redis GUI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: discord-trade-exec-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:devpassword
    ports:
      - '8081:8081'
    networks:
      - trade-exec-network
    depends_on:
      - redis

  # Optional: Mongo Express for MongoDB GUI
  mongo-express:
    image: mongo-express:latest
    container_name: discord-trade-exec-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: devpassword
      ME_CONFIG_MONGODB_URL: mongodb://admin:devpassword@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: devpassword
    ports:
      - '8082:8081'
    networks:
      - trade-exec-network
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  trade-exec-network:
    driver: bridge
