name: Visual Regression Testing

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  visual-regression:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        shard: [1, 2, 3, 4] # Run tests in parallel across 4 shards

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium firefox webkit

      - name: Start application server
        run: |
          npm run build &
          npm start &
          npx wait-on http://localhost:5000 -t 60000
        env:
          NODE_ENV: test
          PORT: 5000

      - name: Run visual regression tests
        run: npx playwright test tests/visual --shard=${{ matrix.shard }}/4 --reporter=html
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shard }}
          path: playwright-report/
          retention-days: 30

      - name: Upload visual diff artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs-${{ matrix.shard }}
          path: |
            tests/visual/__screenshots__/**/*-diff.png
            tests/visual/__screenshots__/**/*-actual.png
          retention-days: 30

  accessibility-audit:
    name: Accessibility Audit
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Start application server
        run: |
          npm run build &
          npm start &
          npx wait-on http://localhost:5000 -t 60000
        env:
          NODE_ENV: test
          PORT: 5000

      - name: Run accessibility tests
        run: npx playwright test tests/visual --grep="Accessibility" --reporter=html
        env:
          CI: true

      - name: Upload accessibility report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: accessibility-report
          path: playwright-report/
          retention-days: 30

  responsive-validation:
    name: Responsive Layout Validation
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Start application server
        run: |
          npm run build &
          npm start &
          npx wait-on http://localhost:5000 -t 60000
        env:
          NODE_ENV: test
          PORT: 5000

      - name: Run responsive tests
        run: npx playwright test tests/visual/responsive --reporter=html
        env:
          CI: true

      - name: Upload responsive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: responsive-test-report
          path: playwright-report/
          retention-days: 30
